### ISSUE TITLE
fix dengste#178

### ISSUE THREAD

**Issue by grauschnabel** [dakra/org-caldav#1]
hi there, can you just show me where and how you fixed dengste#178 ?

**Comment by dakra** [comment]
Hi. When I changed the readme I wanted to mention which PRs are in my fork. I actually mistyped 178 (which isn't even a PR) and fixed my commit message right after but Github is really fast in linking this stuff ;)

But the bug looks interesting. I just tried with a nextcloud server from a friend but couldn't reproduce it. Is there a public nextcloud instance for me to test somewhere or do I have to do something "special" first?

**Comment by grauschnabel** [comment]
Special could be, that you need to have nextcloud behind nginx, where nginx does not accept http requests on https port 443. This seems to be the case mostly by default with nginx. I don't know any public server, but you can have an account on my server to test this. Pm me.

**Comment by dakra** [comment]
Edit: This was actually supposed to be a mail only to you. I send you another one.

---
Hi!

Martin Kaffanke <notifications@github.com> writes:

> Special could be, that you need to have nextcloud behind nginx,
> where nginx does not accept http requests on https port 443. This
> seems to be the case mostly by default with nginx.

Not serving http on 443 by default sounds logical ;)

I was just wondering because someone mentioned having a
one of the hetzner nextcloud instances and that's what my friend
has as well. But obviously I simply added one test appointment
to the calendar and one to my org to play around a bit.
But that worked just fine.

> I don't know any public server, but you can have an account on my
> server to test this. Pm me.

This would be great, thanks.

Cheers,
  Daniel

**Comment by grauschnabel** [comment]
I upgraded to emacs 27.0.50 and now it works. :)

**Comment by dakra** [comment]
Great. Would be nice to now exactly which commit fixed it so we can add a kludge in org-caldav.
But as I don't have the bug I'm not too motivated to invest much more time on it.
Thanks for reporting and testing.
